name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        with:
          version: 10.10.0

      - run: pnpm install
      - run: pnpm build
      - run: pnpm test -- --coverage
      - run: pnpm exec biome check . --rules-default=recommended
      - run: pnpm exec tsc --noEmit
      - run: pnpm exec vite build --emptyOutDir
